name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            python3-setuptools python3-wheel python3-venv \
            libffi-dev libssl-dev libsqlite3-dev \
            zlib1g-dev libjpeg-dev libfreetype6-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Run Buildozer
        run: |
          # buildozer init  # Solo la primera vez, descomenta si es necesario
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Llavero-Soberano
          path: bin/Llavero-Soberano-*.apk
        run: |
          buildozer android debug
      
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Llavero-Soberano
          path: bin/Llavero-Soberano-*.apk
      
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Llavero-Soberano
          path: bin/Llavero-Soberano-*.apk
